// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/rpn_expression.proto

package br.ufc.mdcc.AT04.protobuffer;

public final class RPNProto {
  private RPNProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MElementOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MElement)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double number = 1;</code>
     * @return Whether the number field is set.
     */
    boolean hasNumber();
    /**
     * <code>double number = 1;</code>
     * @return The number.
     */
    double getNumber();

    /**
     * <code>.MElement.EnumOperator operator = 2;</code>
     * @return Whether the operator field is set.
     */
    boolean hasOperator();
    /**
     * <code>.MElement.EnumOperator operator = 2;</code>
     * @return The enum numeric value on the wire for operator.
     */
    int getOperatorValue();
    /**
     * <code>.MElement.EnumOperator operator = 2;</code>
     * @return The operator.
     */
    br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator getOperator();

    public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.ElementOneofCase getElementOneofCase();
  }
  /**
   * Protobuf type {@code MElement}
   */
  public static final class MElement extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MElement)
      MElementOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MElement.newBuilder() to construct.
    private MElement(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MElement() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MElement();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MElement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              elementOneofCase_ = 1;
              elementOneof_ = input.readDouble();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              elementOneofCase_ = 2;
              elementOneof_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.mdcc.AT04.protobuffer.RPNProto.internal_static_MElement_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.mdcc.AT04.protobuffer.RPNProto.internal_static_MElement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.class, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder.class);
    }

    /**
     * Protobuf enum {@code MElement.EnumOperator}
     */
    public enum EnumOperator
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ADDITION = 0;</code>
       */
      ADDITION(0),
      /**
       * <code>SUBTRACTION = 1;</code>
       */
      SUBTRACTION(1),
      /**
       * <code>MULTIPLICATION = 2;</code>
       */
      MULTIPLICATION(2),
      /**
       * <code>DIVISION = 3;</code>
       */
      DIVISION(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ADDITION = 0;</code>
       */
      public static final int ADDITION_VALUE = 0;
      /**
       * <code>SUBTRACTION = 1;</code>
       */
      public static final int SUBTRACTION_VALUE = 1;
      /**
       * <code>MULTIPLICATION = 2;</code>
       */
      public static final int MULTIPLICATION_VALUE = 2;
      /**
       * <code>DIVISION = 3;</code>
       */
      public static final int DIVISION_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static EnumOperator valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static EnumOperator forNumber(int value) {
        switch (value) {
          case 0: return ADDITION;
          case 1: return SUBTRACTION;
          case 2: return MULTIPLICATION;
          case 3: return DIVISION;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EnumOperator>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          EnumOperator> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EnumOperator>() {
              public EnumOperator findValueByNumber(int number) {
                return EnumOperator.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.getDescriptor().getEnumTypes().get(0);
      }

      private static final EnumOperator[] VALUES = values();

      public static EnumOperator valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private EnumOperator(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MElement.EnumOperator)
    }

    private int elementOneofCase_ = 0;
    private java.lang.Object elementOneof_;
    public enum ElementOneofCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      NUMBER(1),
      OPERATOR(2),
      ELEMENTONEOF_NOT_SET(0);
      private final int value;
      private ElementOneofCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ElementOneofCase valueOf(int value) {
        return forNumber(value);
      }

      public static ElementOneofCase forNumber(int value) {
        switch (value) {
          case 1: return NUMBER;
          case 2: return OPERATOR;
          case 0: return ELEMENTONEOF_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ElementOneofCase
    getElementOneofCase() {
      return ElementOneofCase.forNumber(
          elementOneofCase_);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    /**
     * <code>double number = 1;</code>
     * @return Whether the number field is set.
     */
    @java.lang.Override
    public boolean hasNumber() {
      return elementOneofCase_ == 1;
    }
    /**
     * <code>double number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public double getNumber() {
      if (elementOneofCase_ == 1) {
        return (java.lang.Double) elementOneof_;
      }
      return 0D;
    }

    public static final int OPERATOR_FIELD_NUMBER = 2;
    /**
     * <code>.MElement.EnumOperator operator = 2;</code>
     * @return Whether the operator field is set.
     */
    public boolean hasOperator() {
      return elementOneofCase_ == 2;
    }
    /**
     * <code>.MElement.EnumOperator operator = 2;</code>
     * @return The enum numeric value on the wire for operator.
     */
    public int getOperatorValue() {
      if (elementOneofCase_ == 2) {
        return (java.lang.Integer) elementOneof_;
      }
      return 0;
    }
    /**
     * <code>.MElement.EnumOperator operator = 2;</code>
     * @return The operator.
     */
    public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator getOperator() {
      if (elementOneofCase_ == 2) {
        @SuppressWarnings("deprecation")
        br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator result = br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator.valueOf(
            (java.lang.Integer) elementOneof_);
        return result == null ? br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator.UNRECOGNIZED : result;
      }
      return br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator.ADDITION;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (elementOneofCase_ == 1) {
        output.writeDouble(
            1, (double)((java.lang.Double) elementOneof_));
      }
      if (elementOneofCase_ == 2) {
        output.writeEnum(2, ((java.lang.Integer) elementOneof_));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (elementOneofCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              1, (double)((java.lang.Double) elementOneof_));
      }
      if (elementOneofCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, ((java.lang.Integer) elementOneof_));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement)) {
        return super.equals(obj);
      }
      br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement other = (br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement) obj;

      if (!getElementOneofCase().equals(other.getElementOneofCase())) return false;
      switch (elementOneofCase_) {
        case 1:
          if (java.lang.Double.doubleToLongBits(getNumber())
              != java.lang.Double.doubleToLongBits(
                  other.getNumber())) return false;
          break;
        case 2:
          if (getOperatorValue()
              != other.getOperatorValue()) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (elementOneofCase_) {
        case 1:
          hash = (37 * hash) + NUMBER_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getNumber()));
          break;
        case 2:
          hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
          hash = (53 * hash) + getOperatorValue();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MElement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MElement)
        br.ufc.mdcc.AT04.protobuffer.RPNProto.MElementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufc.mdcc.AT04.protobuffer.RPNProto.internal_static_MElement_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufc.mdcc.AT04.protobuffer.RPNProto.internal_static_MElement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.class, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder.class);
      }

      // Construct using br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        elementOneofCase_ = 0;
        elementOneof_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufc.mdcc.AT04.protobuffer.RPNProto.internal_static_MElement_descriptor;
      }

      @java.lang.Override
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement getDefaultInstanceForType() {
        return br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.getDefaultInstance();
      }

      @java.lang.Override
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement build() {
        br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement buildPartial() {
        br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement result = new br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement(this);
        if (elementOneofCase_ == 1) {
          result.elementOneof_ = elementOneof_;
        }
        if (elementOneofCase_ == 2) {
          result.elementOneof_ = elementOneof_;
        }
        result.elementOneofCase_ = elementOneofCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement) {
          return mergeFrom((br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement other) {
        if (other == br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.getDefaultInstance()) return this;
        switch (other.getElementOneofCase()) {
          case NUMBER: {
            setNumber(other.getNumber());
            break;
          }
          case OPERATOR: {
            setOperatorValue(other.getOperatorValue());
            break;
          }
          case ELEMENTONEOF_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int elementOneofCase_ = 0;
      private java.lang.Object elementOneof_;
      public ElementOneofCase
          getElementOneofCase() {
        return ElementOneofCase.forNumber(
            elementOneofCase_);
      }

      public Builder clearElementOneof() {
        elementOneofCase_ = 0;
        elementOneof_ = null;
        onChanged();
        return this;
      }


      /**
       * <code>double number = 1;</code>
       * @return Whether the number field is set.
       */
      public boolean hasNumber() {
        return elementOneofCase_ == 1;
      }
      /**
       * <code>double number = 1;</code>
       * @return The number.
       */
      public double getNumber() {
        if (elementOneofCase_ == 1) {
          return (java.lang.Double) elementOneof_;
        }
        return 0D;
      }
      /**
       * <code>double number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(double value) {
        elementOneofCase_ = 1;
        elementOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        if (elementOneofCase_ == 1) {
          elementOneofCase_ = 0;
          elementOneof_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>.MElement.EnumOperator operator = 2;</code>
       * @return Whether the operator field is set.
       */
      @java.lang.Override
      public boolean hasOperator() {
        return elementOneofCase_ == 2;
      }
      /**
       * <code>.MElement.EnumOperator operator = 2;</code>
       * @return The enum numeric value on the wire for operator.
       */
      @java.lang.Override
      public int getOperatorValue() {
        if (elementOneofCase_ == 2) {
          return ((java.lang.Integer) elementOneof_).intValue();
        }
        return 0;
      }
      /**
       * <code>.MElement.EnumOperator operator = 2;</code>
       * @param value The enum numeric value on the wire for operator to set.
       * @return This builder for chaining.
       */
      public Builder setOperatorValue(int value) {
        elementOneofCase_ = 2;
        elementOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MElement.EnumOperator operator = 2;</code>
       * @return The operator.
       */
      @java.lang.Override
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator getOperator() {
        if (elementOneofCase_ == 2) {
          @SuppressWarnings("deprecation")
          br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator result = br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator.valueOf(
              (java.lang.Integer) elementOneof_);
          return result == null ? br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator.UNRECOGNIZED : result;
        }
        return br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator.ADDITION;
      }
      /**
       * <code>.MElement.EnumOperator operator = 2;</code>
       * @param value The operator to set.
       * @return This builder for chaining.
       */
      public Builder setOperator(br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.EnumOperator value) {
        if (value == null) {
          throw new NullPointerException();
        }
        elementOneofCase_ = 2;
        elementOneof_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MElement.EnumOperator operator = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperator() {
        if (elementOneofCase_ == 2) {
          elementOneofCase_ = 0;
          elementOneof_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MElement)
    }

    // @@protoc_insertion_point(class_scope:MElement)
    private static final br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement();
    }

    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MElement>
        PARSER = new com.google.protobuf.AbstractParser<MElement>() {
      @java.lang.Override
      public MElement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MElement(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MElement> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MElement> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MExpressionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MExpression)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MElement element = 1;</code>
     */
    java.util.List<br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement> 
        getElementList();
    /**
     * <code>repeated .MElement element = 1;</code>
     */
    br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement getElement(int index);
    /**
     * <code>repeated .MElement element = 1;</code>
     */
    int getElementCount();
    /**
     * <code>repeated .MElement element = 1;</code>
     */
    java.util.List<? extends br.ufc.mdcc.AT04.protobuffer.RPNProto.MElementOrBuilder> 
        getElementOrBuilderList();
    /**
     * <code>repeated .MElement element = 1;</code>
     */
    br.ufc.mdcc.AT04.protobuffer.RPNProto.MElementOrBuilder getElementOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MExpression}
   */
  public static final class MExpression extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MExpression)
      MExpressionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MExpression.newBuilder() to construct.
    private MExpression(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MExpression() {
      element_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MExpression();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MExpression(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                element_ = new java.util.ArrayList<br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement>();
                mutable_bitField0_ |= 0x00000001;
              }
              element_.add(
                  input.readMessage(br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          element_ = java.util.Collections.unmodifiableList(element_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.ufc.mdcc.AT04.protobuffer.RPNProto.internal_static_MExpression_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.ufc.mdcc.AT04.protobuffer.RPNProto.internal_static_MExpression_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression.class, br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression.Builder.class);
    }

    public static final int ELEMENT_FIELD_NUMBER = 1;
    private java.util.List<br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement> element_;
    /**
     * <code>repeated .MElement element = 1;</code>
     */
    @java.lang.Override
    public java.util.List<br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement> getElementList() {
      return element_;
    }
    /**
     * <code>repeated .MElement element = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends br.ufc.mdcc.AT04.protobuffer.RPNProto.MElementOrBuilder> 
        getElementOrBuilderList() {
      return element_;
    }
    /**
     * <code>repeated .MElement element = 1;</code>
     */
    @java.lang.Override
    public int getElementCount() {
      return element_.size();
    }
    /**
     * <code>repeated .MElement element = 1;</code>
     */
    @java.lang.Override
    public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement getElement(int index) {
      return element_.get(index);
    }
    /**
     * <code>repeated .MElement element = 1;</code>
     */
    @java.lang.Override
    public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElementOrBuilder getElementOrBuilder(
        int index) {
      return element_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < element_.size(); i++) {
        output.writeMessage(1, element_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < element_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression)) {
        return super.equals(obj);
      }
      br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression other = (br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression) obj;

      if (!getElementList()
          .equals(other.getElementList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getElementCount() > 0) {
        hash = (37 * hash) + ELEMENT_FIELD_NUMBER;
        hash = (53 * hash) + getElementList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MExpression}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MExpression)
        br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpressionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.ufc.mdcc.AT04.protobuffer.RPNProto.internal_static_MExpression_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.ufc.mdcc.AT04.protobuffer.RPNProto.internal_static_MExpression_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression.class, br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression.Builder.class);
      }

      // Construct using br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getElementFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (elementBuilder_ == null) {
          element_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          elementBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.ufc.mdcc.AT04.protobuffer.RPNProto.internal_static_MExpression_descriptor;
      }

      @java.lang.Override
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression getDefaultInstanceForType() {
        return br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression.getDefaultInstance();
      }

      @java.lang.Override
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression build() {
        br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression buildPartial() {
        br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression result = new br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression(this);
        int from_bitField0_ = bitField0_;
        if (elementBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            element_ = java.util.Collections.unmodifiableList(element_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.element_ = element_;
        } else {
          result.element_ = elementBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression) {
          return mergeFrom((br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression other) {
        if (other == br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression.getDefaultInstance()) return this;
        if (elementBuilder_ == null) {
          if (!other.element_.isEmpty()) {
            if (element_.isEmpty()) {
              element_ = other.element_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureElementIsMutable();
              element_.addAll(other.element_);
            }
            onChanged();
          }
        } else {
          if (!other.element_.isEmpty()) {
            if (elementBuilder_.isEmpty()) {
              elementBuilder_.dispose();
              elementBuilder_ = null;
              element_ = other.element_;
              bitField0_ = (bitField0_ & ~0x00000001);
              elementBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getElementFieldBuilder() : null;
            } else {
              elementBuilder_.addAllMessages(other.element_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement> element_ =
        java.util.Collections.emptyList();
      private void ensureElementIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          element_ = new java.util.ArrayList<br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement>(element_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElementOrBuilder> elementBuilder_;

      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public java.util.List<br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement> getElementList() {
        if (elementBuilder_ == null) {
          return java.util.Collections.unmodifiableList(element_);
        } else {
          return elementBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public int getElementCount() {
        if (elementBuilder_ == null) {
          return element_.size();
        } else {
          return elementBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement getElement(int index) {
        if (elementBuilder_ == null) {
          return element_.get(index);
        } else {
          return elementBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public Builder setElement(
          int index, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement value) {
        if (elementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementIsMutable();
          element_.set(index, value);
          onChanged();
        } else {
          elementBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public Builder setElement(
          int index, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder builderForValue) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.set(index, builderForValue.build());
          onChanged();
        } else {
          elementBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public Builder addElement(br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement value) {
        if (elementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementIsMutable();
          element_.add(value);
          onChanged();
        } else {
          elementBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public Builder addElement(
          int index, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement value) {
        if (elementBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureElementIsMutable();
          element_.add(index, value);
          onChanged();
        } else {
          elementBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public Builder addElement(
          br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder builderForValue) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.add(builderForValue.build());
          onChanged();
        } else {
          elementBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public Builder addElement(
          int index, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder builderForValue) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.add(index, builderForValue.build());
          onChanged();
        } else {
          elementBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public Builder addAllElement(
          java.lang.Iterable<? extends br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement> values) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, element_);
          onChanged();
        } else {
          elementBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public Builder clearElement() {
        if (elementBuilder_ == null) {
          element_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          elementBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public Builder removeElement(int index) {
        if (elementBuilder_ == null) {
          ensureElementIsMutable();
          element_.remove(index);
          onChanged();
        } else {
          elementBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder getElementBuilder(
          int index) {
        return getElementFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElementOrBuilder getElementOrBuilder(
          int index) {
        if (elementBuilder_ == null) {
          return element_.get(index);  } else {
          return elementBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public java.util.List<? extends br.ufc.mdcc.AT04.protobuffer.RPNProto.MElementOrBuilder> 
           getElementOrBuilderList() {
        if (elementBuilder_ != null) {
          return elementBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(element_);
        }
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder addElementBuilder() {
        return getElementFieldBuilder().addBuilder(
            br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.getDefaultInstance());
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder addElementBuilder(
          int index) {
        return getElementFieldBuilder().addBuilder(
            index, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.getDefaultInstance());
      }
      /**
       * <code>repeated .MElement element = 1;</code>
       */
      public java.util.List<br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder> 
           getElementBuilderList() {
        return getElementFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElementOrBuilder> 
          getElementFieldBuilder() {
        if (elementBuilder_ == null) {
          elementBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElement.Builder, br.ufc.mdcc.AT04.protobuffer.RPNProto.MElementOrBuilder>(
                  element_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          element_ = null;
        }
        return elementBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MExpression)
    }

    // @@protoc_insertion_point(class_scope:MExpression)
    private static final br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression();
    }

    public static br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MExpression>
        PARSER = new com.google.protobuf.AbstractParser<MExpression>() {
      @java.lang.Override
      public MExpression parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MExpression(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MExpression> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MExpression> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.ufc.mdcc.AT04.protobuffer.RPNProto.MExpression getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MElement_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MElement_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MExpression_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MExpression_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036resources/rpn_expression.proto\"\252\001\n\010MEl" +
      "ement\022\020\n\006number\030\001 \001(\001H\000\022*\n\010operator\030\002 \001(" +
      "\0162\026.MElement.EnumOperatorH\000\"O\n\014EnumOpera" +
      "tor\022\014\n\010ADDITION\020\000\022\017\n\013SUBTRACTION\020\001\022\022\n\016MU" +
      "LTIPLICATION\020\002\022\014\n\010DIVISION\020\003B\017\n\relement_" +
      "oneof\")\n\013MExpression\022\032\n\007element\030\001 \003(\0132\t." +
      "MElementB(\n\034br.ufc.mdcc.AT04.protobuffer" +
      "B\010RPNProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MElement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MElement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MElement_descriptor,
        new java.lang.String[] { "Number", "Operator", "ElementOneof", });
    internal_static_MExpression_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MExpression_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MExpression_descriptor,
        new java.lang.String[] { "Element", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
