// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/filme.proto

package old.protobuftutorial;

public final class FilmeProto {
  private FilmeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MFilmeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MFilme)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string titulo = 2;</code>
     * @return The titulo.
     */
    java.lang.String getTitulo();
    /**
     * <code>string titulo = 2;</code>
     * @return The bytes for titulo.
     */
    com.google.protobuf.ByteString
        getTituloBytes();

    /**
     * <code>int32 ano = 3;</code>
     * @return The ano.
     */
    int getAno();

    /**
     * <code>int32 avaliacao_imdb = 4;</code>
     * @return The avaliacaoImdb.
     */
    int getAvaliacaoImdb();

    /**
     * <code>string link_trailer = 5;</code>
     * @return The linkTrailer.
     */
    java.lang.String getLinkTrailer();
    /**
     * <code>string link_trailer = 5;</code>
     * @return The bytes for linkTrailer.
     */
    com.google.protobuf.ByteString
        getLinkTrailerBytes();

    /**
     * <code>repeated .MFilme filmes_relacionados = 6;</code>
     */
    java.util.List<old.protobuftutorial.FilmeProto.MFilme> 
        getFilmesRelacionadosList();
    /**
     * <code>repeated .MFilme filmes_relacionados = 6;</code>
     */
    old.protobuftutorial.FilmeProto.MFilme getFilmesRelacionados(int index);
    /**
     * <code>repeated .MFilme filmes_relacionados = 6;</code>
     */
    int getFilmesRelacionadosCount();
    /**
     * <code>repeated .MFilme filmes_relacionados = 6;</code>
     */
    java.util.List<? extends old.protobuftutorial.FilmeProto.MFilmeOrBuilder> 
        getFilmesRelacionadosOrBuilderList();
    /**
     * <code>repeated .MFilme filmes_relacionados = 6;</code>
     */
    old.protobuftutorial.FilmeProto.MFilmeOrBuilder getFilmesRelacionadosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MFilme}
   */
  public static final class MFilme extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MFilme)
      MFilmeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MFilme.newBuilder() to construct.
    private MFilme(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MFilme() {
      titulo_ = "";
      linkTrailer_ = "";
      filmesRelacionados_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MFilme();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MFilme(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              titulo_ = s;
              break;
            }
            case 24: {

              ano_ = input.readInt32();
              break;
            }
            case 32: {

              avaliacaoImdb_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              linkTrailer_ = s;
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                filmesRelacionados_ = new java.util.ArrayList<old.protobuftutorial.FilmeProto.MFilme>();
                mutable_bitField0_ |= 0x00000001;
              }
              filmesRelacionados_.add(
                  input.readMessage(old.protobuftutorial.FilmeProto.MFilme.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          filmesRelacionados_ = java.util.Collections.unmodifiableList(filmesRelacionados_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return old.protobuftutorial.FilmeProto.internal_static_MFilme_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return old.protobuftutorial.FilmeProto.internal_static_MFilme_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              old.protobuftutorial.FilmeProto.MFilme.class, old.protobuftutorial.FilmeProto.MFilme.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int TITULO_FIELD_NUMBER = 2;
    private volatile java.lang.Object titulo_;
    /**
     * <code>string titulo = 2;</code>
     * @return The titulo.
     */
    @java.lang.Override
    public java.lang.String getTitulo() {
      java.lang.Object ref = titulo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        titulo_ = s;
        return s;
      }
    }
    /**
     * <code>string titulo = 2;</code>
     * @return The bytes for titulo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTituloBytes() {
      java.lang.Object ref = titulo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        titulo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANO_FIELD_NUMBER = 3;
    private int ano_;
    /**
     * <code>int32 ano = 3;</code>
     * @return The ano.
     */
    @java.lang.Override
    public int getAno() {
      return ano_;
    }

    public static final int AVALIACAO_IMDB_FIELD_NUMBER = 4;
    private int avaliacaoImdb_;
    /**
     * <code>int32 avaliacao_imdb = 4;</code>
     * @return The avaliacaoImdb.
     */
    @java.lang.Override
    public int getAvaliacaoImdb() {
      return avaliacaoImdb_;
    }

    public static final int LINK_TRAILER_FIELD_NUMBER = 5;
    private volatile java.lang.Object linkTrailer_;
    /**
     * <code>string link_trailer = 5;</code>
     * @return The linkTrailer.
     */
    @java.lang.Override
    public java.lang.String getLinkTrailer() {
      java.lang.Object ref = linkTrailer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        linkTrailer_ = s;
        return s;
      }
    }
    /**
     * <code>string link_trailer = 5;</code>
     * @return The bytes for linkTrailer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLinkTrailerBytes() {
      java.lang.Object ref = linkTrailer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        linkTrailer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILMES_RELACIONADOS_FIELD_NUMBER = 6;
    private java.util.List<old.protobuftutorial.FilmeProto.MFilme> filmesRelacionados_;
    /**
     * <code>repeated .MFilme filmes_relacionados = 6;</code>
     */
    @java.lang.Override
    public java.util.List<old.protobuftutorial.FilmeProto.MFilme> getFilmesRelacionadosList() {
      return filmesRelacionados_;
    }
    /**
     * <code>repeated .MFilme filmes_relacionados = 6;</code>
     */
    @java.lang.Override
    public java.util.List<? extends old.protobuftutorial.FilmeProto.MFilmeOrBuilder> 
        getFilmesRelacionadosOrBuilderList() {
      return filmesRelacionados_;
    }
    /**
     * <code>repeated .MFilme filmes_relacionados = 6;</code>
     */
    @java.lang.Override
    public int getFilmesRelacionadosCount() {
      return filmesRelacionados_.size();
    }
    /**
     * <code>repeated .MFilme filmes_relacionados = 6;</code>
     */
    @java.lang.Override
    public old.protobuftutorial.FilmeProto.MFilme getFilmesRelacionados(int index) {
      return filmesRelacionados_.get(index);
    }
    /**
     * <code>repeated .MFilme filmes_relacionados = 6;</code>
     */
    @java.lang.Override
    public old.protobuftutorial.FilmeProto.MFilmeOrBuilder getFilmesRelacionadosOrBuilder(
        int index) {
      return filmesRelacionados_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getTituloBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, titulo_);
      }
      if (ano_ != 0) {
        output.writeInt32(3, ano_);
      }
      if (avaliacaoImdb_ != 0) {
        output.writeInt32(4, avaliacaoImdb_);
      }
      if (!getLinkTrailerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, linkTrailer_);
      }
      for (int i = 0; i < filmesRelacionados_.size(); i++) {
        output.writeMessage(6, filmesRelacionados_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getTituloBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, titulo_);
      }
      if (ano_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ano_);
      }
      if (avaliacaoImdb_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, avaliacaoImdb_);
      }
      if (!getLinkTrailerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, linkTrailer_);
      }
      for (int i = 0; i < filmesRelacionados_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, filmesRelacionados_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof old.protobuftutorial.FilmeProto.MFilme)) {
        return super.equals(obj);
      }
      old.protobuftutorial.FilmeProto.MFilme other = (old.protobuftutorial.FilmeProto.MFilme) obj;

      if (getId()
          != other.getId()) return false;
      if (!getTitulo()
          .equals(other.getTitulo())) return false;
      if (getAno()
          != other.getAno()) return false;
      if (getAvaliacaoImdb()
          != other.getAvaliacaoImdb()) return false;
      if (!getLinkTrailer()
          .equals(other.getLinkTrailer())) return false;
      if (!getFilmesRelacionadosList()
          .equals(other.getFilmesRelacionadosList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + TITULO_FIELD_NUMBER;
      hash = (53 * hash) + getTitulo().hashCode();
      hash = (37 * hash) + ANO_FIELD_NUMBER;
      hash = (53 * hash) + getAno();
      hash = (37 * hash) + AVALIACAO_IMDB_FIELD_NUMBER;
      hash = (53 * hash) + getAvaliacaoImdb();
      hash = (37 * hash) + LINK_TRAILER_FIELD_NUMBER;
      hash = (53 * hash) + getLinkTrailer().hashCode();
      if (getFilmesRelacionadosCount() > 0) {
        hash = (37 * hash) + FILMES_RELACIONADOS_FIELD_NUMBER;
        hash = (53 * hash) + getFilmesRelacionadosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static old.protobuftutorial.FilmeProto.MFilme parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static old.protobuftutorial.FilmeProto.MFilme parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(old.protobuftutorial.FilmeProto.MFilme prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MFilme}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MFilme)
        old.protobuftutorial.FilmeProto.MFilmeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return old.protobuftutorial.FilmeProto.internal_static_MFilme_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return old.protobuftutorial.FilmeProto.internal_static_MFilme_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                old.protobuftutorial.FilmeProto.MFilme.class, old.protobuftutorial.FilmeProto.MFilme.Builder.class);
      }

      // Construct using protobuftutorial.FilmeProto.MFilme.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFilmesRelacionadosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        titulo_ = "";

        ano_ = 0;

        avaliacaoImdb_ = 0;

        linkTrailer_ = "";

        if (filmesRelacionadosBuilder_ == null) {
          filmesRelacionados_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          filmesRelacionadosBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return old.protobuftutorial.FilmeProto.internal_static_MFilme_descriptor;
      }

      @java.lang.Override
      public old.protobuftutorial.FilmeProto.MFilme getDefaultInstanceForType() {
        return old.protobuftutorial.FilmeProto.MFilme.getDefaultInstance();
      }

      @java.lang.Override
      public old.protobuftutorial.FilmeProto.MFilme build() {
        old.protobuftutorial.FilmeProto.MFilme result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public old.protobuftutorial.FilmeProto.MFilme buildPartial() {
        old.protobuftutorial.FilmeProto.MFilme result = new old.protobuftutorial.FilmeProto.MFilme(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.titulo_ = titulo_;
        result.ano_ = ano_;
        result.avaliacaoImdb_ = avaliacaoImdb_;
        result.linkTrailer_ = linkTrailer_;
        if (filmesRelacionadosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            filmesRelacionados_ = java.util.Collections.unmodifiableList(filmesRelacionados_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.filmesRelacionados_ = filmesRelacionados_;
        } else {
          result.filmesRelacionados_ = filmesRelacionadosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof old.protobuftutorial.FilmeProto.MFilme) {
          return mergeFrom((old.protobuftutorial.FilmeProto.MFilme)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(old.protobuftutorial.FilmeProto.MFilme other) {
        if (other == old.protobuftutorial.FilmeProto.MFilme.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getTitulo().isEmpty()) {
          titulo_ = other.titulo_;
          onChanged();
        }
        if (other.getAno() != 0) {
          setAno(other.getAno());
        }
        if (other.getAvaliacaoImdb() != 0) {
          setAvaliacaoImdb(other.getAvaliacaoImdb());
        }
        if (!other.getLinkTrailer().isEmpty()) {
          linkTrailer_ = other.linkTrailer_;
          onChanged();
        }
        if (filmesRelacionadosBuilder_ == null) {
          if (!other.filmesRelacionados_.isEmpty()) {
            if (filmesRelacionados_.isEmpty()) {
              filmesRelacionados_ = other.filmesRelacionados_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFilmesRelacionadosIsMutable();
              filmesRelacionados_.addAll(other.filmesRelacionados_);
            }
            onChanged();
          }
        } else {
          if (!other.filmesRelacionados_.isEmpty()) {
            if (filmesRelacionadosBuilder_.isEmpty()) {
              filmesRelacionadosBuilder_.dispose();
              filmesRelacionadosBuilder_ = null;
              filmesRelacionados_ = other.filmesRelacionados_;
              bitField0_ = (bitField0_ & ~0x00000001);
              filmesRelacionadosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFilmesRelacionadosFieldBuilder() : null;
            } else {
              filmesRelacionadosBuilder_.addAllMessages(other.filmesRelacionados_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        old.protobuftutorial.FilmeProto.MFilme parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (old.protobuftutorial.FilmeProto.MFilme) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object titulo_ = "";
      /**
       * <code>string titulo = 2;</code>
       * @return The titulo.
       */
      public java.lang.String getTitulo() {
        java.lang.Object ref = titulo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          titulo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string titulo = 2;</code>
       * @return The bytes for titulo.
       */
      public com.google.protobuf.ByteString
          getTituloBytes() {
        java.lang.Object ref = titulo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          titulo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string titulo = 2;</code>
       * @param value The titulo to set.
       * @return This builder for chaining.
       */
      public Builder setTitulo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        titulo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string titulo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitulo() {
        
        titulo_ = getDefaultInstance().getTitulo();
        onChanged();
        return this;
      }
      /**
       * <code>string titulo = 2;</code>
       * @param value The bytes for titulo to set.
       * @return This builder for chaining.
       */
      public Builder setTituloBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        titulo_ = value;
        onChanged();
        return this;
      }

      private int ano_ ;
      /**
       * <code>int32 ano = 3;</code>
       * @return The ano.
       */
      @java.lang.Override
      public int getAno() {
        return ano_;
      }
      /**
       * <code>int32 ano = 3;</code>
       * @param value The ano to set.
       * @return This builder for chaining.
       */
      public Builder setAno(int value) {
        
        ano_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ano = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAno() {
        
        ano_ = 0;
        onChanged();
        return this;
      }

      private int avaliacaoImdb_ ;
      /**
       * <code>int32 avaliacao_imdb = 4;</code>
       * @return The avaliacaoImdb.
       */
      @java.lang.Override
      public int getAvaliacaoImdb() {
        return avaliacaoImdb_;
      }
      /**
       * <code>int32 avaliacao_imdb = 4;</code>
       * @param value The avaliacaoImdb to set.
       * @return This builder for chaining.
       */
      public Builder setAvaliacaoImdb(int value) {
        
        avaliacaoImdb_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 avaliacao_imdb = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvaliacaoImdb() {
        
        avaliacaoImdb_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object linkTrailer_ = "";
      /**
       * <code>string link_trailer = 5;</code>
       * @return The linkTrailer.
       */
      public java.lang.String getLinkTrailer() {
        java.lang.Object ref = linkTrailer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          linkTrailer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string link_trailer = 5;</code>
       * @return The bytes for linkTrailer.
       */
      public com.google.protobuf.ByteString
          getLinkTrailerBytes() {
        java.lang.Object ref = linkTrailer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          linkTrailer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string link_trailer = 5;</code>
       * @param value The linkTrailer to set.
       * @return This builder for chaining.
       */
      public Builder setLinkTrailer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        linkTrailer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string link_trailer = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLinkTrailer() {
        
        linkTrailer_ = getDefaultInstance().getLinkTrailer();
        onChanged();
        return this;
      }
      /**
       * <code>string link_trailer = 5;</code>
       * @param value The bytes for linkTrailer to set.
       * @return This builder for chaining.
       */
      public Builder setLinkTrailerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        linkTrailer_ = value;
        onChanged();
        return this;
      }

      private java.util.List<old.protobuftutorial.FilmeProto.MFilme> filmesRelacionados_ =
        java.util.Collections.emptyList();
      private void ensureFilmesRelacionadosIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          filmesRelacionados_ = new java.util.ArrayList<old.protobuftutorial.FilmeProto.MFilme>(filmesRelacionados_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          old.protobuftutorial.FilmeProto.MFilme, old.protobuftutorial.FilmeProto.MFilme.Builder, old.protobuftutorial.FilmeProto.MFilmeOrBuilder> filmesRelacionadosBuilder_;

      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public java.util.List<old.protobuftutorial.FilmeProto.MFilme> getFilmesRelacionadosList() {
        if (filmesRelacionadosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(filmesRelacionados_);
        } else {
          return filmesRelacionadosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public int getFilmesRelacionadosCount() {
        if (filmesRelacionadosBuilder_ == null) {
          return filmesRelacionados_.size();
        } else {
          return filmesRelacionadosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public old.protobuftutorial.FilmeProto.MFilme getFilmesRelacionados(int index) {
        if (filmesRelacionadosBuilder_ == null) {
          return filmesRelacionados_.get(index);
        } else {
          return filmesRelacionadosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public Builder setFilmesRelacionados(
          int index, old.protobuftutorial.FilmeProto.MFilme value) {
        if (filmesRelacionadosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilmesRelacionadosIsMutable();
          filmesRelacionados_.set(index, value);
          onChanged();
        } else {
          filmesRelacionadosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public Builder setFilmesRelacionados(
          int index, old.protobuftutorial.FilmeProto.MFilme.Builder builderForValue) {
        if (filmesRelacionadosBuilder_ == null) {
          ensureFilmesRelacionadosIsMutable();
          filmesRelacionados_.set(index, builderForValue.build());
          onChanged();
        } else {
          filmesRelacionadosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public Builder addFilmesRelacionados(old.protobuftutorial.FilmeProto.MFilme value) {
        if (filmesRelacionadosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilmesRelacionadosIsMutable();
          filmesRelacionados_.add(value);
          onChanged();
        } else {
          filmesRelacionadosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public Builder addFilmesRelacionados(
          int index, old.protobuftutorial.FilmeProto.MFilme value) {
        if (filmesRelacionadosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilmesRelacionadosIsMutable();
          filmesRelacionados_.add(index, value);
          onChanged();
        } else {
          filmesRelacionadosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public Builder addFilmesRelacionados(
          old.protobuftutorial.FilmeProto.MFilme.Builder builderForValue) {
        if (filmesRelacionadosBuilder_ == null) {
          ensureFilmesRelacionadosIsMutable();
          filmesRelacionados_.add(builderForValue.build());
          onChanged();
        } else {
          filmesRelacionadosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public Builder addFilmesRelacionados(
          int index, old.protobuftutorial.FilmeProto.MFilme.Builder builderForValue) {
        if (filmesRelacionadosBuilder_ == null) {
          ensureFilmesRelacionadosIsMutable();
          filmesRelacionados_.add(index, builderForValue.build());
          onChanged();
        } else {
          filmesRelacionadosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public Builder addAllFilmesRelacionados(
          java.lang.Iterable<? extends old.protobuftutorial.FilmeProto.MFilme> values) {
        if (filmesRelacionadosBuilder_ == null) {
          ensureFilmesRelacionadosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, filmesRelacionados_);
          onChanged();
        } else {
          filmesRelacionadosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public Builder clearFilmesRelacionados() {
        if (filmesRelacionadosBuilder_ == null) {
          filmesRelacionados_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          filmesRelacionadosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public Builder removeFilmesRelacionados(int index) {
        if (filmesRelacionadosBuilder_ == null) {
          ensureFilmesRelacionadosIsMutable();
          filmesRelacionados_.remove(index);
          onChanged();
        } else {
          filmesRelacionadosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public old.protobuftutorial.FilmeProto.MFilme.Builder getFilmesRelacionadosBuilder(
          int index) {
        return getFilmesRelacionadosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public old.protobuftutorial.FilmeProto.MFilmeOrBuilder getFilmesRelacionadosOrBuilder(
          int index) {
        if (filmesRelacionadosBuilder_ == null) {
          return filmesRelacionados_.get(index);  } else {
          return filmesRelacionadosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public java.util.List<? extends old.protobuftutorial.FilmeProto.MFilmeOrBuilder> 
           getFilmesRelacionadosOrBuilderList() {
        if (filmesRelacionadosBuilder_ != null) {
          return filmesRelacionadosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(filmesRelacionados_);
        }
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public old.protobuftutorial.FilmeProto.MFilme.Builder addFilmesRelacionadosBuilder() {
        return getFilmesRelacionadosFieldBuilder().addBuilder(
            old.protobuftutorial.FilmeProto.MFilme.getDefaultInstance());
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public old.protobuftutorial.FilmeProto.MFilme.Builder addFilmesRelacionadosBuilder(
          int index) {
        return getFilmesRelacionadosFieldBuilder().addBuilder(
            index, old.protobuftutorial.FilmeProto.MFilme.getDefaultInstance());
      }
      /**
       * <code>repeated .MFilme filmes_relacionados = 6;</code>
       */
      public java.util.List<old.protobuftutorial.FilmeProto.MFilme.Builder> 
           getFilmesRelacionadosBuilderList() {
        return getFilmesRelacionadosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          old.protobuftutorial.FilmeProto.MFilme, old.protobuftutorial.FilmeProto.MFilme.Builder, old.protobuftutorial.FilmeProto.MFilmeOrBuilder> 
          getFilmesRelacionadosFieldBuilder() {
        if (filmesRelacionadosBuilder_ == null) {
          filmesRelacionadosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              old.protobuftutorial.FilmeProto.MFilme, old.protobuftutorial.FilmeProto.MFilme.Builder, old.protobuftutorial.FilmeProto.MFilmeOrBuilder>(
                  filmesRelacionados_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          filmesRelacionados_ = null;
        }
        return filmesRelacionadosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MFilme)
    }

    // @@protoc_insertion_point(class_scope:MFilme)
    private static final old.protobuftutorial.FilmeProto.MFilme DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new old.protobuftutorial.FilmeProto.MFilme();
    }

    public static old.protobuftutorial.FilmeProto.MFilme getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MFilme>
        PARSER = new com.google.protobuf.AbstractParser<MFilme>() {
      @java.lang.Override
      public MFilme parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MFilme(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MFilme> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MFilme> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public old.protobuftutorial.FilmeProto.MFilme getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MListaFilmesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MListaFilmes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .MFilme filmes = 1;</code>
     */
    java.util.List<old.protobuftutorial.FilmeProto.MFilme> 
        getFilmesList();
    /**
     * <code>repeated .MFilme filmes = 1;</code>
     */
    old.protobuftutorial.FilmeProto.MFilme getFilmes(int index);
    /**
     * <code>repeated .MFilme filmes = 1;</code>
     */
    int getFilmesCount();
    /**
     * <code>repeated .MFilme filmes = 1;</code>
     */
    java.util.List<? extends old.protobuftutorial.FilmeProto.MFilmeOrBuilder> 
        getFilmesOrBuilderList();
    /**
     * <code>repeated .MFilme filmes = 1;</code>
     */
    old.protobuftutorial.FilmeProto.MFilmeOrBuilder getFilmesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code MListaFilmes}
   */
  public static final class MListaFilmes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MListaFilmes)
      MListaFilmesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MListaFilmes.newBuilder() to construct.
    private MListaFilmes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MListaFilmes() {
      filmes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MListaFilmes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MListaFilmes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                filmes_ = new java.util.ArrayList<old.protobuftutorial.FilmeProto.MFilme>();
                mutable_bitField0_ |= 0x00000001;
              }
              filmes_.add(
                  input.readMessage(old.protobuftutorial.FilmeProto.MFilme.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          filmes_ = java.util.Collections.unmodifiableList(filmes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return old.protobuftutorial.FilmeProto.internal_static_MListaFilmes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return old.protobuftutorial.FilmeProto.internal_static_MListaFilmes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              old.protobuftutorial.FilmeProto.MListaFilmes.class, old.protobuftutorial.FilmeProto.MListaFilmes.Builder.class);
    }

    public static final int FILMES_FIELD_NUMBER = 1;
    private java.util.List<old.protobuftutorial.FilmeProto.MFilme> filmes_;
    /**
     * <code>repeated .MFilme filmes = 1;</code>
     */
    @java.lang.Override
    public java.util.List<old.protobuftutorial.FilmeProto.MFilme> getFilmesList() {
      return filmes_;
    }
    /**
     * <code>repeated .MFilme filmes = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends old.protobuftutorial.FilmeProto.MFilmeOrBuilder> 
        getFilmesOrBuilderList() {
      return filmes_;
    }
    /**
     * <code>repeated .MFilme filmes = 1;</code>
     */
    @java.lang.Override
    public int getFilmesCount() {
      return filmes_.size();
    }
    /**
     * <code>repeated .MFilme filmes = 1;</code>
     */
    @java.lang.Override
    public old.protobuftutorial.FilmeProto.MFilme getFilmes(int index) {
      return filmes_.get(index);
    }
    /**
     * <code>repeated .MFilme filmes = 1;</code>
     */
    @java.lang.Override
    public old.protobuftutorial.FilmeProto.MFilmeOrBuilder getFilmesOrBuilder(
        int index) {
      return filmes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < filmes_.size(); i++) {
        output.writeMessage(1, filmes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < filmes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, filmes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof old.protobuftutorial.FilmeProto.MListaFilmes)) {
        return super.equals(obj);
      }
      old.protobuftutorial.FilmeProto.MListaFilmes other = (old.protobuftutorial.FilmeProto.MListaFilmes) obj;

      if (!getFilmesList()
          .equals(other.getFilmesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFilmesCount() > 0) {
        hash = (37 * hash) + FILMES_FIELD_NUMBER;
        hash = (53 * hash) + getFilmesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static old.protobuftutorial.FilmeProto.MListaFilmes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static old.protobuftutorial.FilmeProto.MListaFilmes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(old.protobuftutorial.FilmeProto.MListaFilmes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MListaFilmes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MListaFilmes)
        old.protobuftutorial.FilmeProto.MListaFilmesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return old.protobuftutorial.FilmeProto.internal_static_MListaFilmes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return old.protobuftutorial.FilmeProto.internal_static_MListaFilmes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                old.protobuftutorial.FilmeProto.MListaFilmes.class, old.protobuftutorial.FilmeProto.MListaFilmes.Builder.class);
      }

      // Construct using protobuftutorial.FilmeProto.MListaFilmes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFilmesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (filmesBuilder_ == null) {
          filmes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          filmesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return old.protobuftutorial.FilmeProto.internal_static_MListaFilmes_descriptor;
      }

      @java.lang.Override
      public old.protobuftutorial.FilmeProto.MListaFilmes getDefaultInstanceForType() {
        return old.protobuftutorial.FilmeProto.MListaFilmes.getDefaultInstance();
      }

      @java.lang.Override
      public old.protobuftutorial.FilmeProto.MListaFilmes build() {
        old.protobuftutorial.FilmeProto.MListaFilmes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public old.protobuftutorial.FilmeProto.MListaFilmes buildPartial() {
        old.protobuftutorial.FilmeProto.MListaFilmes result = new old.protobuftutorial.FilmeProto.MListaFilmes(this);
        int from_bitField0_ = bitField0_;
        if (filmesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            filmes_ = java.util.Collections.unmodifiableList(filmes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.filmes_ = filmes_;
        } else {
          result.filmes_ = filmesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof old.protobuftutorial.FilmeProto.MListaFilmes) {
          return mergeFrom((old.protobuftutorial.FilmeProto.MListaFilmes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(old.protobuftutorial.FilmeProto.MListaFilmes other) {
        if (other == old.protobuftutorial.FilmeProto.MListaFilmes.getDefaultInstance()) return this;
        if (filmesBuilder_ == null) {
          if (!other.filmes_.isEmpty()) {
            if (filmes_.isEmpty()) {
              filmes_ = other.filmes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFilmesIsMutable();
              filmes_.addAll(other.filmes_);
            }
            onChanged();
          }
        } else {
          if (!other.filmes_.isEmpty()) {
            if (filmesBuilder_.isEmpty()) {
              filmesBuilder_.dispose();
              filmesBuilder_ = null;
              filmes_ = other.filmes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              filmesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFilmesFieldBuilder() : null;
            } else {
              filmesBuilder_.addAllMessages(other.filmes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        old.protobuftutorial.FilmeProto.MListaFilmes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (old.protobuftutorial.FilmeProto.MListaFilmes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<old.protobuftutorial.FilmeProto.MFilme> filmes_ =
        java.util.Collections.emptyList();
      private void ensureFilmesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          filmes_ = new java.util.ArrayList<old.protobuftutorial.FilmeProto.MFilme>(filmes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          old.protobuftutorial.FilmeProto.MFilme, old.protobuftutorial.FilmeProto.MFilme.Builder, old.protobuftutorial.FilmeProto.MFilmeOrBuilder> filmesBuilder_;

      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public java.util.List<old.protobuftutorial.FilmeProto.MFilme> getFilmesList() {
        if (filmesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(filmes_);
        } else {
          return filmesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public int getFilmesCount() {
        if (filmesBuilder_ == null) {
          return filmes_.size();
        } else {
          return filmesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public old.protobuftutorial.FilmeProto.MFilme getFilmes(int index) {
        if (filmesBuilder_ == null) {
          return filmes_.get(index);
        } else {
          return filmesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public Builder setFilmes(
          int index, old.protobuftutorial.FilmeProto.MFilme value) {
        if (filmesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilmesIsMutable();
          filmes_.set(index, value);
          onChanged();
        } else {
          filmesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public Builder setFilmes(
          int index, old.protobuftutorial.FilmeProto.MFilme.Builder builderForValue) {
        if (filmesBuilder_ == null) {
          ensureFilmesIsMutable();
          filmes_.set(index, builderForValue.build());
          onChanged();
        } else {
          filmesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public Builder addFilmes(old.protobuftutorial.FilmeProto.MFilme value) {
        if (filmesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilmesIsMutable();
          filmes_.add(value);
          onChanged();
        } else {
          filmesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public Builder addFilmes(
          int index, old.protobuftutorial.FilmeProto.MFilme value) {
        if (filmesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilmesIsMutable();
          filmes_.add(index, value);
          onChanged();
        } else {
          filmesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public Builder addFilmes(
          old.protobuftutorial.FilmeProto.MFilme.Builder builderForValue) {
        if (filmesBuilder_ == null) {
          ensureFilmesIsMutable();
          filmes_.add(builderForValue.build());
          onChanged();
        } else {
          filmesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public Builder addFilmes(
          int index, old.protobuftutorial.FilmeProto.MFilme.Builder builderForValue) {
        if (filmesBuilder_ == null) {
          ensureFilmesIsMutable();
          filmes_.add(index, builderForValue.build());
          onChanged();
        } else {
          filmesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public Builder addAllFilmes(
          java.lang.Iterable<? extends old.protobuftutorial.FilmeProto.MFilme> values) {
        if (filmesBuilder_ == null) {
          ensureFilmesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, filmes_);
          onChanged();
        } else {
          filmesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public Builder clearFilmes() {
        if (filmesBuilder_ == null) {
          filmes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          filmesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public Builder removeFilmes(int index) {
        if (filmesBuilder_ == null) {
          ensureFilmesIsMutable();
          filmes_.remove(index);
          onChanged();
        } else {
          filmesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public old.protobuftutorial.FilmeProto.MFilme.Builder getFilmesBuilder(
          int index) {
        return getFilmesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public old.protobuftutorial.FilmeProto.MFilmeOrBuilder getFilmesOrBuilder(
          int index) {
        if (filmesBuilder_ == null) {
          return filmes_.get(index);  } else {
          return filmesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public java.util.List<? extends old.protobuftutorial.FilmeProto.MFilmeOrBuilder> 
           getFilmesOrBuilderList() {
        if (filmesBuilder_ != null) {
          return filmesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(filmes_);
        }
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public old.protobuftutorial.FilmeProto.MFilme.Builder addFilmesBuilder() {
        return getFilmesFieldBuilder().addBuilder(
            old.protobuftutorial.FilmeProto.MFilme.getDefaultInstance());
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public old.protobuftutorial.FilmeProto.MFilme.Builder addFilmesBuilder(
          int index) {
        return getFilmesFieldBuilder().addBuilder(
            index, old.protobuftutorial.FilmeProto.MFilme.getDefaultInstance());
      }
      /**
       * <code>repeated .MFilme filmes = 1;</code>
       */
      public java.util.List<old.protobuftutorial.FilmeProto.MFilme.Builder> 
           getFilmesBuilderList() {
        return getFilmesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          old.protobuftutorial.FilmeProto.MFilme, old.protobuftutorial.FilmeProto.MFilme.Builder, old.protobuftutorial.FilmeProto.MFilmeOrBuilder> 
          getFilmesFieldBuilder() {
        if (filmesBuilder_ == null) {
          filmesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              old.protobuftutorial.FilmeProto.MFilme, old.protobuftutorial.FilmeProto.MFilme.Builder, old.protobuftutorial.FilmeProto.MFilmeOrBuilder>(
                  filmes_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          filmes_ = null;
        }
        return filmesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MListaFilmes)
    }

    // @@protoc_insertion_point(class_scope:MListaFilmes)
    private static final old.protobuftutorial.FilmeProto.MListaFilmes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new old.protobuftutorial.FilmeProto.MListaFilmes();
    }

    public static old.protobuftutorial.FilmeProto.MListaFilmes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MListaFilmes>
        PARSER = new com.google.protobuf.AbstractParser<MListaFilmes>() {
      @java.lang.Override
      public MListaFilmes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MListaFilmes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MListaFilmes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MListaFilmes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public old.protobuftutorial.FilmeProto.MListaFilmes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MFilme_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MFilme_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MListaFilmes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MListaFilmes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025resources/filme.proto\"\205\001\n\006MFilme\022\n\n\002id" +
      "\030\001 \001(\005\022\016\n\006titulo\030\002 \001(\t\022\013\n\003ano\030\003 \001(\005\022\026\n\016a" +
      "valiacao_imdb\030\004 \001(\005\022\024\n\014link_trailer\030\005 \001(" +
      "\t\022$\n\023filmes_relacionados\030\006 \003(\0132\007.MFilme\"" +
      "\'\n\014MListaFilmes\022\027\n\006filmes\030\001 \003(\0132\007.MFilme" +
      "B\036\n\020protobuftutorialB\nFilmeProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MFilme_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MFilme_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MFilme_descriptor,
        new java.lang.String[] { "Id", "Titulo", "Ano", "AvaliacaoImdb", "LinkTrailer", "FilmesRelacionados", });
    internal_static_MListaFilmes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MListaFilmes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MListaFilmes_descriptor,
        new java.lang.String[] { "Filmes", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
